export const EVENTS = {
    STATUS_CHANGED: 'STATUS_CHANGED',
    GOOGLE_JUMPED: 'GOOGLE_JUMPED',
    GOOGLE_ESCAPED: 'GOOGLE_ESCAPED',
    PLAYER_MOVED: 'PLAYER_MOVED',
    GOOGLE_WAS_CATCHED: 'GOOGLE_WAS_CATCHED'
}